#!/usr/bin/env python

import velimonde_providers

# To skip a module, simply remove the corresponding key in the options dict
# To keep it without passing any options, set the correponding value to {}
options = {
        'tfl_london' : { 'url' : '<TfL data feed url here>' },
        'jcdecaux' : { 'api_key' : '<your JCDecaux API key here>' } }

velimonde_providers.update_all(options)
